### PR TITLE
Remove non sectors code

### PR DESCRIPTION
**Pull request by camillebaldock**
I heartily recommend to review this one commit by commit!
See it in action -> https://sectors-only-prototype.herokuapp.com/

### CODE REVIEW

**Comment by camillebaldock** [comment]
## What's in there?
- Deleted _all of the code_ from other apps
- Modified config to work without these apps
- Edited environment variables to keep only ones necessary from sectors
- Moved error view to sectors application
- Moved report generation and email sending to synchronous, out of async tasks

## What will come in future PRs
- remove need for PrinceXML
- final cleanup of celery/prince/helper code
- documentation for running this on AWS
- copy and formatting of email reports
- check analytics setup
- check cookie warning message copy, and that it works properly

**Comment by camillebaldock** [comment]
# New copy in pictures:

## Page 1

page1

## Page 1 with validation errors

page1-witherror

## Page 2

page2

## Page 2 with validation error

page2-witherror

## Page 3

page3

## Page 3 with validation error

page3-error

## Page 3 with success

page3-success

**Comment by gjvis** [comment]
Looks good, but why synchronous email sending?

**Comment by camillebaldock** [comment]
@gjvis so that I can containerise this without need for Redis/queue as a first stab at pushing this to AWS. Commits left intentionally separate so we can come back on that decision. 
I don't feel that given the use case (5 to 10 users) planned in the first instance, this is the worst decision. If you're concerned and would rather we set up a MQ upfront lmk.

**Comment by gjvis** [comment]
I don't think we need redis to run celery if we aren't using locks or chords (which we aren't for email).

**Comment by camillebaldock** [comment]
@gjvis if celery without Redis/RabbitMQ/other, I'm not sure what you have in mind?

**Comment by gjvis** [comment]
haha, yes you are right. commenting on PRs the day after the christmas party = fail

**Comment by gjvis** [comment]
:+1:

**Comment by camillebaldock** [comment]
@gjvis ooooh I had forgotten about :christmas_tree: :tada: :-D

**Comment by camillebaldock** [comment]
@gjvis so based on this conversation, my plan for action after this is:
- remove need for PrinceXML
- run this on AWS and push the Docker setup _somewhere_ (repo yet to be determined)
- documentation for running this on AWS in Confluence
- copy and formatting of email reports
- check analytics setup
- check cookie warning message copy, and that it works properly
- bring back asynchronous emails, and update docs/Docker config/all that good stuff to make it work

Give me a shout if that isn't what you had pictured.

**Comment by gjvis** [comment]
a most excellent plan

**Pull request merged**
