### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by camillebaldock**
## Still to do (future PR):
- elasticbeanstalk setup and docs

### CODE REVIEW

**Comment by gjvis** [comment]
worked for me, although I believe Nathan had problems installing docker via self-service

**Comment by nathancashmoredwp** [comment]
Would be good to know what the pre-requisites are for this with respect to running the above commands as step 1 "install docker: it's in the self service" is not even an option, even after speaking with Calum.  More notes to follow once i've worked it out.

**Comment by nathancashmoredwp** [comment]
:+1:

**Comment by gjvis** [comment]
:shipit: :ship: :rocket: :100: :metal:

**Pull request merged**
